services:
  biunote:
    image: ghcr.io/thief-k/biu-note:1.0.3
    container_name: biunote
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - LOGIN_TOKEN=biunote-secret-token
      - TZ=Asia/Shanghai
    volumes:
      - ./notes:/app/notes

